<?php

/**
 * In your lackey files you will have to include the autoloader generated by
 * composer.  This allows lackey to find it's classes, dependencies, and any
 * plugins.
 */
include __DIR__ . '/vendor/autoload.php';

use Lackey\Task;

/**
 * Initialize a new lackey instance.
 */
$lackey = new \Lackey\Lackey();

/**
 * Use the loadTask method to use a predefined task and configure it.
 */
$lackey->loadTask(new Task\Exec(), array(
    'phpunit' => array(
        'command' => 'vendor/bin/phpunit -c tests/phpunit.xml',
    ),
    'ls' => array(
        'command' => 'ls',
    ),
));

/**
 * Use the task method to define a function lackey will call.
 */
$lackey->task('say-hello', 'Says hello to the world.  But really just to yourself.', function () {
    echo "Hello World!\n\n";
});

/**
 * The default method sets the lackey commands that will be ran if no commands
 * are given.
 */
$lackey->default(array(
    'say-hello', 'exec:phpunit',
));

/**
 * The alias method allows you to set up a command that when used will invoke
 * other lackey commands.
 */
$lackey->alias('build', 'Builds the application.', array(
    'exec:phpunit',
));
